<#
.SYNOPSIS
  Guarded create/update/delete workflow for user data types and folders.
.DESCRIPTION
  The caller supplies a JSON plan. UI focus, context-menu commands, dialog input,
  clipboard paste, save, and copy-back verification are owned here. The runner
  never creates anything under the (System) branch.
#>
param(
  [Parameter(Mandatory=$true)][string]$ProjectPath,
  [Parameter(Mandatory=$true)][string]$PlanPath,
  [Parameter(Mandatory=$true)][string]$OutDir
)
$ErrorActionPreference='Stop'
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$runLog=Join-Path $OutDir 'run.log'; $env:KV_WORKFLOW_RUN_LOG=$runLog
function Log([string]$Type,[hashtable]$Data=@{}) { $o=[ordered]@{timestamp=(Get-Date).ToString('o');type=$Type}; foreach($k in $Data.Keys){$o[$k]=$Data[$k]}; (ConvertTo-Json $o -Compress)|Add-Content -LiteralPath $runLog -Encoding UTF8 }
function Fail([string]$Code,[string]$Message,[object[]]$Evidence=@()) { Log 'workflow_failed' @{error_code=$Code;message=$Message;evidence=$Evidence}; [ordered]@{ok=$false;error_code=$Code;message=$Message;evidence=@($Evidence)}|ConvertTo-Json -Depth 12|Set-Content -LiteralPath (Join-Path $OutDir 'failure.json') -Encoding UTF8; throw "$Code`: $Message" }
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName UIAutomationClient
$scriptRoot=Split-Path -Parent (Split-Path -Parent $PSCommandPath)
. (Join-Path $scriptRoot 'guards\kv_ui_guard.ps1')
Initialize-KvUiGuard -OutDir $OutDir
$script:ExpectedTitle='KV STUDIO*'; $script:MainHwnd=[IntPtr]::Zero; $script:ProjectPid=0
function FindProjectProcess {
  $needle=[IO.Path]::GetFileNameWithoutExtension($ProjectPath)
  $target=[IO.Path]::GetFullPath($ProjectPath)
  $ids=@(Get-CimInstance Win32_Process -Filter "Name='Kvs.exe'" -ErrorAction SilentlyContinue|Where-Object {[string]$_.CommandLine -like "*$target*"}|ForEach-Object {[int]$_.ProcessId})
  $ps=@(Get-Process Kvs -ErrorAction SilentlyContinue|Where-Object {$_.MainWindowHandle -ne 0 -and (($ids -contains $_.Id) -or $_.MainWindowTitle -like "*$needle*")})
  if($ids.Count -eq 1){$ps=@(Get-Process -Id $ids[0] -ErrorAction SilentlyContinue|Where-Object {$_.MainWindowHandle -ne 0})}
  if($ps.Count -ne 1){Fail 'KV_PROJECT_WINDOW_AMBIGUOUS' "Expected one KV STUDIO window for $needle, got $($ps.Count)"}
  return $ps[0]
}
function Tree([int]$PidValue){$root=[Windows.Automation.AutomationElement]::RootElement; $t=$root.FindFirst([Windows.Automation.TreeScope]::Descendants,(New-Object Windows.Automation.AndCondition((New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::ProcessIdProperty,$PidValue)),(New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::AutomationIdProperty,'ProjectTreeView'))))); if(-not $t){Fail 'KV_PROJECT_TREE_MISSING' 'ProjectTreeView was not found'}; return $t}
function ExpandDataTypes([Windows.Automation.AutomationElement]$T){$typeRoot=-join([char[]](0x6570,0x636E,0x7C7B,0x578B));$cond=New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::ControlTypeProperty,[Windows.Automation.ControlType]::TreeItem);$walker=[Windows.Automation.TreeWalker]::ControlViewWalker;for($pass=0;$pass -lt 5;$pass++){$items=$T.FindAll([Windows.Automation.TreeScope]::Descendants,$cond);$changed=$false;foreach($i in $items){$under=([string]$i.Current.Name -eq $typeRoot);$p=$walker.GetParent($i);for($n=0;$p -and $n -lt 20;$n++){if([string]$p.Current.Name -eq $typeRoot){$under=$true;break};$p=$walker.GetParent($p)};if(-not $under){continue};$ep=$null;if($i.TryGetCurrentPattern([Windows.Automation.ExpandCollapsePattern]::Pattern,[ref]$ep) -and $ep.Current.ExpandCollapseState -eq [Windows.Automation.ExpandCollapseState]::Collapsed){$ep.Expand();$changed=$true;Start-Sleep -Milliseconds 60}};if(-not $changed){break}};Log 'data_type_tree_expanded' @{}
}
function ItemPath([Windows.Automation.AutomationElement]$Item){$walker=[Windows.Automation.TreeWalker]::ControlViewWalker;$parts=@([string]$Item.Current.Name);$p=$walker.GetParent($Item);for($i=0;$p -and $i -lt 20;$i++){if($p.Current.ControlType -eq [Windows.Automation.ControlType]::TreeItem){$parts=@([string]$p.Current.Name)+$parts};$p=$walker.GetParent($p)};return @($parts)}
function FindItem([Windows.Automation.AutomationElement]$T,[string[]]$Path){$all=$T.FindAll([Windows.Automation.TreeScope]::Descendants,(New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::ControlTypeProperty,[Windows.Automation.ControlType]::TreeItem)));if($Path.Count -eq 1){$hits=@($all|Where-Object {[string]$_.Current.Name -eq [string]$Path[0]})}else{$hits=@($all|Where-Object {$p=ItemPath $_; if($p.Count -lt $Path.Count){return $false}; $offset=$p.Count-$Path.Count; for($i=0;$i -lt $Path.Count;$i++){$actual=([string]$p[$offset+$i] -split ':',2)[0].Trim();if($actual -ne [string]$Path[$i]){return $false}}; return $true})}; if($hits.Count -ne 1){return $null};return $hits[0]}
function SelectItem([Windows.Automation.AutomationElement]$T,[string[]]$Path,[string]$Label){$item=FindItem $T $Path;if(-not $item){Fail 'KV_STRUCTURE_TREE_ITEM_NOT_FOUND' "Tree item not found: $($Path -join '/')"};try{$s=$null;if($item.TryGetCurrentPattern([Windows.Automation.ScrollItemPattern]::Pattern,[ref]$s)){$s.ScrollIntoView()}}catch{};Assert-KvUiForegroundHwnd -ExpectedHwnd $script:MainHwnd -Step "select $Label" -ExpectedTitleLike $script:ExpectedTitle -AllowSingleRecovery|Out-Null;$sel=$null;if($item.TryGetCurrentPattern([Windows.Automation.SelectionItemPattern]::Pattern,[ref]$sel)){$sel.Select()}else{Fail 'KV_STRUCTURE_TREE_SELECT_UNAVAILABLE' "Tree item is not selectable: $($Path -join '/')"};Start-Sleep -Milliseconds 80;return $item}
function UserTypeNames([Windows.Automation.AutomationElement]$T){$typeRoot=-join([char[]](0x6570,0x636E,0x7C7B,0x578B));$all=$T.FindAll([Windows.Automation.TreeScope]::Descendants,(New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::ControlTypeProperty,[Windows.Automation.ControlType]::TreeItem)));$walker=[Windows.Automation.TreeWalker]::ControlViewWalker;$out=@();foreach($i in $all){$n=[string]$i.Current.Name;if(-not $n -or $n -eq '(System)'){continue};$p=$walker.GetParent($i);$under=$false;$system=$false;for($j=0;$p -and $j -lt 20;$j++){$pn=[string]$p.Current.Name;if($pn -eq $typeRoot){$under=$true};if($pn -eq '(System)'){$system=$true};$p=$walker.GetParent($p)};$ep=$null;$isContainer=$i.TryGetCurrentPattern([Windows.Automation.ExpandCollapsePattern]::Pattern,[ref]$ep);if($under -and -not $system -and -not $isContainer){$out+=($n -split ':',2)[0].Trim()}};return @($out|Sort-Object -Unique)}
function WaitDialog([string]$Kind){$deadline=(Get-Date).AddSeconds(5);do{$fg=Get-KvForegroundSnapshot;if($fg.process_id -eq $script:ProjectPid -and $fg.hwnd -ne $script:MainHwnd -and ((-not $Kind) -or $fg.title -like "*$Kind*")){$hwnd=[IntPtr]$fg.hwnd;Log 'dialog_foreground_verified' @{kind=$Kind;hwnd=$hwnd.ToInt64();title=$fg.title;focus_policy='KV STUDIO locks name field automatically; no focus navigation'};return $hwnd};Start-Sleep -Milliseconds 80}while((Get-Date)-lt $deadline);Fail 'KV_STRUCTURE_DIALOG_TIMEOUT' "Dialog not found: $Kind"}
function DialogEdit([Windows.Automation.AutomationElement]$D){$e=$D.FindFirst([Windows.Automation.TreeScope]::Descendants,(New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::ControlTypeProperty,[Windows.Automation.ControlType]::Edit)));if(-not $e){Fail 'KV_STRUCTURE_DIALOG_EDIT_MISSING' "Edit control not found in dialog $($D.Current.Name)"};return $e}
function WaitEditor([string]$Name){$deadline=(Get-Date).AddSeconds(5);do{$root=[Windows.Automation.AutomationElement]::RootElement;$panels=$root.FindAll([Windows.Automation.TreeScope]::Descendants,(New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::AutomationIdProperty,'_pnlMain')));$p=@($panels|Where-Object {$_.Current.ProcessId -eq $script:ProjectPid}|Select-Object -First 1);if($p){$tabItems=$root.FindAll([Windows.Automation.TreeScope]::Descendants,(New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::ControlTypeProperty,[Windows.Automation.ControlType]::TabItem)));$tabs=@($tabItems|Where-Object {$_.Current.ProcessId -eq $script:ProjectPid -and $_.Current.Name -match [regex]::Escape($Name)});if($tabs.Count -gt 0){return $p}};Start-Sleep -Milliseconds 100}while((Get-Date)-lt $deadline);Fail 'KV_STRUCTURE_EDITOR_TIMEOUT' "Structure editor not ready: $Name"}
function FocusGrid([Windows.Automation.AutomationElement]$Surface,[string]$Name){$r=$Surface.Current.BoundingRectangle;if($r.Width -lt 300 -or $r.Height -lt 200){Fail 'KV_STRUCTURE_GRID_MISSING' $Name};Invoke-KvGuardedMouseClick -TargetHwnd $script:MainHwnd -Step "focus structure grid $Name" -X ([int]($r.X+110)) -Y ([int]($r.Y+28)) -ExpectedTitleLike $script:ExpectedTitle -SleepMs 60;Invoke-KvGuardedSendKeys -TargetHwnd $script:MainHwnd -Step "exit structure edit $Name" -Keys '{ESC}' -ExpectedTitleLike $script:ExpectedTitle -SleepMs 40;Invoke-KvGuardedSendKeys -TargetHwnd $script:MainHwnd -Step "move structure grid home $Name" -Keys '^{HOME}' -ExpectedTitleLike $script:ExpectedTitle -SleepMs 40}
function CopyGrid([string]$Name){Invoke-KvGuardedSendKeys -TargetHwnd $script:MainHwnd -Step "select structure grid $Name" -Keys '^+{END}' -ExpectedTitleLike $script:ExpectedTitle -SleepMs 60;Invoke-KvGuardedSendKeys -TargetHwnd $script:MainHwnd -Step "copy structure grid $Name" -Keys '^c' -ExpectedTitleLike $script:ExpectedTitle -SleepMs 120;$text=[Windows.Forms.Clipboard]::GetText();if([string]::IsNullOrWhiteSpace($text)){Fail 'KV_STRUCTURE_COPYBACK_EMPTY' "Empty copy-back for $Name"};return $text}
function ParseMembers([string]$Text){$out=@();foreach($line in @($Text -split "`r?`n"|Where-Object {$_.Trim()})){ $f=@($line -split "`t"); if($f.Count -lt 2){continue};$out += [ordered]@{name=([string]$f[0]).Trim([char]0xFEFF).Trim();data_type=([string]$f[1]).Trim();raw_columns=$f} };return @($out)}
function MembersText([object[]]$Members){$lines=@();foreach($m in @($Members)){if(-not $m.name -or -not $m.data_type){Fail 'KV_STRUCTURE_MEMBER_INVALID' 'Every member requires name and data_type'};$raw=@($m.raw_columns);if($raw.Count -lt 2){$raw=@([string]$m.name,[string]$m.data_type,'','','','','','');if($m.comment_1){$raw[4]=[string]$m.comment_1};if($m.comment_2){$raw[5]=[string]$m.comment_2}}else{$raw[0]=[string]$m.name;$raw[1]=[string]$m.data_type};$lines+=($raw -join "`t")};return (($lines -join "`r`n")+"`r`n")}
function PasteMembers([string]$Name,[object[]]$Members){$text=MembersText $Members;Invoke-KvGuardedClipboardSetText -TargetHwnd $script:MainHwnd -Step "set structure payload $Name" -Text $text -ExpectedTitleLike $script:ExpectedTitle;Invoke-KvGuardedSendKeys -TargetHwnd $script:MainHwnd -Step "paste structure members $Name" -Keys '^v' -ExpectedTitleLike $script:ExpectedTitle -SleepMs 180}
function SaveClose([string]$Name){Invoke-KvGuardedSendKeys -TargetHwnd $script:MainHwnd -Step "save structure $Name" -Keys '^s' -ExpectedTitleLike $script:ExpectedTitle -SleepMs 250;Invoke-KvGuardedSendKeys -TargetHwnd $script:MainHwnd -Step "close structure editor $Name" -Keys '^{F4}' -ExpectedTitleLike $script:ExpectedTitle -SleepMs 180}
function OpenStructure([Windows.Automation.AutomationElement]$T,[string[]]$Path,[string]$Name){SelectItem $T $Path "select structure $Name"|Out-Null;Invoke-KvGuardedSendKeys -TargetHwnd $script:MainHwnd -Step "open structure $Name" -Keys '{ENTER}' -ExpectedTitleLike $script:ExpectedTitle -SleepMs 180;Log 'structure_grid_auto_focus_assumed' @{name=$Name;action='enter opens type and focuses grid top-left'};return $true}
function WaitContextMenuItems([int]$PidValue){$deadline=(Get-Date).AddSeconds(2);do{$root=[Windows.Automation.AutomationElement]::RootElement;$menus=$root.FindAll([Windows.Automation.TreeScope]::Descendants,(New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::ControlTypeProperty,[Windows.Automation.ControlType]::MenuItem)));$items=@($menus|Where-Object {$_.Current.ProcessId -eq $PidValue -and [string]$_.Current.AccessKey -notlike 'Alt+*'});if(@($items|Where-Object {$_.Current.IsEnabled -and ([string]$_.Current.AccessKey -eq 'f' -or [string]$_.Current.AccessKey -eq 'r')}).Count -gt 0){return $items};Start-Sleep -Milliseconds 80}while((Get-Date)-lt $deadline);return @($items)}
function ContextCommand([Windows.Automation.AutomationElement]$T,[string[]]$Parent,[string]$Key,[string]$Label){$item=SelectItem $T $Parent "context target $Label";$r=$item.Current.BoundingRectangle;Log 'context_target_bounds' @{label=$Label;x=$r.X;y=$r.Y;width=$r.Width;height=$r.Height;offscreen=$item.Current.IsOffscreen};Invoke-KvGuardedMouseClick -TargetHwnd $script:MainHwnd -Step "focus context target $Label" -X ([int]($r.X+$r.Width/2)) -Y ([int]($r.Y+$r.Height/2)) -ExpectedTitleLike $script:ExpectedTitle -SleepMs 180;Invoke-KvGuardedMouseRightClick -TargetHwnd $script:MainHwnd -Step "open context menu $Label" -X ([int]($r.X+$r.Width/2)) -Y ([int]($r.Y+$r.Height/2)) -ExpectedTitleLike $script:ExpectedTitle -SleepMs 180;$same=@(WaitContextMenuItems $script:ProjectPid);$summary=@($same|ForEach-Object {[ordered]@{name=[string]$_.Current.Name;access=[string]$_.Current.AccessKey;enabled=$_.Current.IsEnabled;offscreen=$_.Current.IsOffscreen}});Log 'context_menu_items' @{label=$Label;items=$summary};$candidate=@($same|Where-Object {$_.Current.IsEnabled -and [string]$_.Current.AccessKey -eq $Key});if($candidate.Count -ne 1){Fail 'KV_STRUCTURE_CONTEXT_COMMAND_NOT_FOUND' "Enabled context-menu command '$Key' was not uniquely exposed for $Label"};Invoke-KvGuardedSendKeysAllowTargetClose -TargetHwnd $script:MainHwnd -Step "invoke context command $Label" -Keys $Key -ExpectedTitleLike $script:ExpectedTitle -SuccessTitleLike @('*新建*',$script:ExpectedTitle) -Action 'invoke selected project-tree context command by access key' -SleepMs 180;Log 'context_command_invoked' @{label=$Label;key=$Key;route='guarded_access_key'}}
function CreateFolder([Windows.Automation.AutomationElement]$T,[string[]]$Parent,[string]$Name){ContextCommand $T $Parent 'f' "create folder $Name";$newTitle=-join([char[]](0x65B0,0x5EFA));$dh=[IntPtr](WaitDialog $newTitle);Log 'dialog_input_begin' @{name=$Name;policy='direct paste then enter; no focus navigation'};Invoke-KvGuardedClipboardPaste -TargetHwnd $dh -Step "paste folder name $Name" -Text $Name -ExpectedTitleLike '*';Invoke-KvGuardedSendKeysAllowTargetClose -TargetHwnd $dh -Step "enter folder name $Name" -Keys '{ENTER}' -ExpectedTitleLike '*' -SuccessTitleLike @('*','KV STUDIO*') -Action 'enter automatically focused folder name' -SleepMs 250;Log 'folder_created' @{name=$Name;parent=($Parent -join '/')}}
function VerifyStructure([Windows.Automation.AutomationElement]$T,[string[]]$Path,[object[]]$Expected){$name=[string]$Path[-1];OpenStructure $T $Path $name|Out-Null;$actual=ParseMembers (CopyGrid $name);$expected=@($Expected|ForEach-Object {[ordered]@{name=[string]$_.name;data_type=[string]$_.data_type}});$pairs=@();foreach($e in $expected){$a=@($actual|Where-Object {$_.name -eq $e.name -and $_.data_type -eq $e.data_type});if($a.Count -ne 1){$pairs+="$($e.name):$($e.data_type)"}};SaveClose $name;if($pairs.Count -gt 0 -or $actual.Count -ne $expected.Count){Fail 'KV_STRUCTURE_MUTATION_NOT_PERSISTED' "Structure $name readback mismatch. missing=$($pairs -join ',');actual_count=$($actual.Count);expected_count=$($expected.Count)"};Log 'structure_copyback_verified' @{name=$name;member_count=$actual.Count}}
function CreateStructure([Windows.Automation.AutomationElement]$T,[string[]]$Parent,[object]$Op){$name=[string]$Op.name;ContextCommand $T $Parent 'r' "create data type $name";$newTypeTitle=-join([char[]](0x65B0,0x5EFA,0x6570,0x636E,0x7C7B,0x578B));$dh=[IntPtr](WaitDialog $newTypeTitle);Log 'dialog_input_begin' @{name=$name;policy='automatic name focus; paste then confirm'};Invoke-KvGuardedClipboardPaste -TargetHwnd $dh -Step "paste data type name $name" -Text $name -ExpectedTitleLike '*';if([string]$Op.kind -eq 'tuple'){Invoke-KvGuardedSendKeys -TargetHwnd $dh -Step "select tuple kind $name" -Keys '%p{DOWN}' -ExpectedTitleLike '*' -SleepMs 50};Invoke-KvGuardedSendKeysAllowTargetClose -TargetHwnd $dh -Step "confirm data type $name" -Keys '{ENTER}' -ExpectedTitleLike '*' -SuccessTitleLike @('*','KV STUDIO*') -Action 'confirm new data type; editor grid receives focus automatically' -SleepMs 180;Log 'structure_grid_auto_focus_assumed' @{name=$name;action='paste members directly after create dialog confirmation'};PasteMembers $name @($Op.members);SaveClose $name;Log 'structure_created' @{name=$name;parent=($Parent -join '/');kind=[string]$Op.kind;verification='saved after direct grid paste'}}
function UpdateStructure([Windows.Automation.AutomationElement]$T,[string[]]$Path,[object]$Op){$name=[string]$Op.name;OpenStructure $T $Path $name|Out-Null;PasteMembers $name @($Op.members);SaveClose $name;VerifyStructure (Tree $script:ProjectPid) $Path @($Op.members);Log 'structure_updated' @{name=$name;path=($Path -join '/')}}
function DeleteStructure([Windows.Automation.AutomationElement]$T,[string[]]$Path,[object]$Op){$name=[string]$Op.name;ContextCommand $T $Path 'd' "delete structure $name";$deadline=(Get-Date).AddSeconds(4);$fg=$null;do{$fg=Get-KvForegroundSnapshot;if($fg.process_id -eq $script:ProjectPid -and $fg.hwnd -ne $script:MainHwnd -and $fg.title -match '删除|确认|确定'){break};Start-Sleep -Milliseconds 80}while((Get-Date)-lt $deadline);if(-not $fg -or $fg.hwnd -eq $script:MainHwnd){Fail 'KV_STRUCTURE_DELETE_CONFIRMATION_MISSING' "Delete confirmation dialog not found for $name"};$dh=[IntPtr]$fg.hwnd;Log 'delete_dialog_foreground_verified' @{name=$name;hwnd=$dh.ToInt64();policy='default cancel; left then enter'};Invoke-KvGuardedSendKeys -TargetHwnd $dh -Step "select delete confirm button $name" -Keys '{LEFT}' -ExpectedTitleLike '*' -SleepMs 60;Invoke-KvGuardedSendKeysAllowTargetClose -TargetHwnd $dh -Step "confirm delete structure $name" -Keys '{ENTER}' -ExpectedTitleLike '*' -SuccessTitleLike @('*','KV STUDIO*') -Action 'confirm delete data type after left from default cancel' -SleepMs 250;Start-Sleep -Milliseconds 180;$check=FindItem (Tree $script:ProjectPid) $Path;if($check){Fail 'KV_STRUCTURE_DELETE_NOT_PERSISTED' "Structure still present after delete: $name"};Log 'structure_deleted' @{name=$name;path=($Path -join '/')}}
function BaseType([string]$Type){$t=$Type.Trim();if($t -match '^ARRAY\[[^]]+\]\s+OF\s+(.+)$'){$t=$Matches[1].Trim()};return $t}
function ValidatePlan([object]$Plan,[string[]]$Existing){$known=@{};foreach($n in $Existing){$known[$n]=$true};foreach($o in @($Plan.structure_operations)){if([string]$o.name -match '^$' -or [string]$o.name -eq '(System)'){Fail 'KV_STRUCTURE_NAME_INVALID' 'A structure name is empty or reserved'};if([string]$o.path -match '\(System\)' -or @($o.parent_path)-contains '(System)'){Fail 'KV_SYSTEM_BRANCH_READ_ONLY' "System data types cannot be changed: $($o.name)"};$action=[string]$o.action;if($action -eq 'create'){if($known.ContainsKey([string]$o.name)){Fail 'KV_STRUCTURE_NAME_CONFLICT' "Structure already exists or is duplicated: $($o.name)"};$known[[string]$o.name]=$true}elseif($action -ne 'update' -and $action -ne 'delete'){Fail 'KV_STRUCTURE_ACTION_INVALID' "Unsupported structure action: $action"}}}
$plan=Get-Content -Raw -LiteralPath $PlanPath -Encoding UTF8|ConvertFrom-Json
$p=FindProjectProcess;$script:ProjectPid=$p.Id;$script:MainHwnd=[IntPtr]$p.MainWindowHandle;Assert-KvUiForegroundHwnd -ExpectedHwnd $script:MainHwnd -Step 'structure mutation preflight' -ExpectedTitleLike $script:ExpectedTitle -AllowSingleRecovery|Out-Null;$t=Tree $script:ProjectPid;$existing=@();Log 'preflight_passed' @{existing_type_count=0;mode='targeted_paths_only'}
ValidatePlan $plan $existing
try{
  foreach($f in @($plan.folder_operations)){if([string]$f.action -ne 'create'){Fail 'KV_STRUCTURE_FOLDER_ACTION_INVALID' "Unsupported folder action: $($f.action)"};if([string]$f.name -eq '(System)' -or @($f.parent_path)-contains '(System)'){Fail 'KV_SYSTEM_BRANCH_READ_ONLY' 'System branch cannot be changed'};CreateFolder $t @($f.parent_path) ([string]$f.name);$t=Tree $script:ProjectPid}
  foreach($o in @($plan.structure_operations)){$parent=@($o.parent_path);$path=@($parent+([string]$o.name));switch([string]$o.action){'create'{CreateStructure $t $parent $o};'update'{UpdateStructure $t $path $o};'delete'{DeleteStructure $t $path $o}};$t=Tree $script:ProjectPid}
  $result=[ordered]@{ok=$true;project_path=$ProjectPath;plan_path=$PlanPath;folder_operations=@($plan.folder_operations).Count;structure_operations=@($plan.structure_operations).Count;existing_types_before=$existing;generated_at=(Get-Date).ToString('o')};$result|ConvertTo-Json -Depth 12|Set-Content -LiteralPath (Join-Path $OutDir 'result.json') -Encoding UTF8;Log 'workflow_finished' @{ok=$true;structure_operations=$result.structure_operations}
}catch{if(-not (Test-Path (Join-Path $OutDir 'failure.json'))){[ordered]@{ok=$false;error_code='KV_STRUCTURE_MUTATION_FAILED';message=$_.Exception.Message}|ConvertTo-Json|Set-Content (Join-Path $OutDir 'failure.json') -Encoding UTF8};throw}

