param([Parameter(Mandatory=$true)][string]$ProjectPath,[Parameter(Mandatory=$true)][string]$FbModuleName,[Parameter(Mandatory=$true)][string]$MnmPath,[Parameter(Mandatory=$true)][string]$OutDir)
$ErrorActionPreference='Stop';New-Item -ItemType Directory -Force $OutDir|Out-Null
. (Join-Path (Split-Path -Parent $PSCommandPath) '..\guards\kv_ui_guard.ps1');Add-Type -AssemblyName System.Windows.Forms;Add-Type -AssemblyName UIAutomationClient;Add-Type -AssemblyName UIAutomationTypes
Initialize-KvUiGuard -OutDir $OutDir -CheckpointSubdir 'program_body_ui'
$projectNeedle=[IO.Path]::GetFileNameWithoutExtension([IO.Path]::GetFullPath($ProjectPath));$p=@(Get-Process Kvs -ErrorAction SilentlyContinue|Where-Object {$_.MainWindowTitle -like 'KV STUDIO*' -and $_.MainWindowHandle -ne 0 -and $_.MainWindowTitle -like "*$projectNeedle*"});if($p.Count -ne 1){if($p.Count -eq 0){throw 'KV_PROJECT_PROCESS_NOT_FOUND'};throw 'KV_TARGET_PROJECT_WINDOW_AMBIGUOUS'};$p=$p[0];$root=[Windows.Automation.AutomationElement]::FromHandle($p.MainWindowHandle);$cond=New-Object Windows.Automation.PropertyCondition -ArgumentList ([Windows.Automation.AutomationElement]::AutomationIdProperty,'ProjectTreeView');$tree=$root.FindFirst([Windows.Automation.TreeScope]::Descendants,$cond);if(!$tree){throw 'KV_PROJECT_TREE_MISSING'}
$items=$tree.FindAll([Windows.Automation.TreeScope]::Descendants,(New-Object Windows.Automation.PropertyCondition -ArgumentList ([Windows.Automation.AutomationElement]::ControlTypeProperty,[Windows.Automation.ControlType]::TreeItem)));$item=$null;for($i=0;$i -lt $items.Count;$i++){$n=[string]$items.Item($i).Current.Name;if($n -eq $FbModuleName -or $n.StartsWith($FbModuleName+':',[StringComparison]::Ordinal) -or $n.StartsWith($FbModuleName+' [',[StringComparison]::Ordinal)){$item=$items.Item($i);break}};if(!$item){throw 'KV_MODULE_NOT_FOUND'};$sel=$null;if($item.TryGetCurrentPattern([Windows.Automation.SelectionItemPattern]::Pattern,[ref]$sel)){$sel.Select()};$item.SetFocus()
foreach($s in @(@('open','{ENTER}',700),@('end','^{END}',180),@('up','{UP}',180),@('select','^+{HOME}',250),@('delete','{DELETE}',450))){Invoke-KvGuardedSendKeys -TargetHwnd $p.MainWindowHandle -Step "program_body_$($s[0])" -Keys $s[1] -ExpectedTitleLike 'KV STUDIO*' -SleepMs $s[2]}
Invoke-KvGuardedCtrlChord -TargetHwnd $p.MainWindowHandle -Step 'program_body_open_edit_list' -Vk 0x44 -ExpectedTitleLike 'KV STUDIO*' -AllowModalAfter -SleepMs 500
$root=[Windows.Automation.AutomationElement]::FromHandle($p.MainWindowHandle);$insertCond=New-Object Windows.Automation.PropertyCondition -ArgumentList ([Windows.Automation.AutomationElement]::AutomationIdProperty,'_buttonInsert');$insertButton=$root.FindFirst([Windows.Automation.TreeScope]::Descendants,$insertCond);if(-not $insertButton){throw 'KV_EDIT_LIST_MODAL_NOT_FOUND'};Write-KvUiGuardRunLog -Event 'program_body_edit_list_embedded_detected' -Data @{insert_button_hwnd=$insertButton.Current.NativeWindowHandle;foreground_hwnd=(Get-KvForegroundSnapshot).hwnd;mode='embedded_panel'};$dh=[IntPtr]$p.MainWindowHandle;$text=(Get-Content $MnmPath -Encoding Default|Where-Object {$_ -notmatch '^;MODULE' -and $_ -notmatch '^DEVICE:'})-join "`r`n";Invoke-KvGuardedClipboardPaste -TargetHwnd $dh -Step 'program_body_paste' -Text $text -ExpectedTitleLike 'KV STUDIO*' -SleepMs 400;Invoke-KvGuardedSendKeys -TargetHwnd $dh -Step 'program_body_tab_insert' -Keys '{TAB}' -ExpectedTitleLike 'KV STUDIO*' -SleepMs 100;Invoke-KvGuardedSendKeys -TargetHwnd $dh -Step 'program_body_insert' -Keys '{ENTER}' -ExpectedTitleLike 'KV STUDIO*' -SleepMs 700;$post=Get-KvForegroundSnapshot;if($post.class_name -eq '#32770' -and $post.process_id -eq $p.Id){ $ed=[Windows.Automation.AutomationElement]::FromHandle([IntPtr]$post.hwnd);$errorText=$post.title;try{$ns=$ed.FindAll([Windows.Automation.TreeScope]::Descendants,[Windows.Automation.Condition]::TrueCondition);for($j=0;$j -lt $ns.Count;$j++){if([string]$ns.Item($j).Current.Name){$errorText+=' | '+$ns.Item($j).Current.Name}}}catch{};Write-KvUiGuardRunLog -Event 'program_body_insert_error_modal' -Data @{text=$errorText;hwnd=$post.hwnd};Invoke-KvGuardedSendKeysAllowTargetClose -TargetHwnd ([IntPtr]$post.hwnd) -Step 'dismiss program body error' -Keys '{ENTER}' -ExpectedTitleLike '*' -SuccessTitleLike @('*') -SleepMs 300;if([KvSharedUiGuardWin32]::IsWindow($dh)){Invoke-KvGuardedSendKeysAllowTargetClose -TargetHwnd $dh -Step 'close edit list after error' -Keys '%{F4}' -ExpectedTitleLike 'KV STUDIO*' -SuccessTitleLike @('KV STUDIO*') -SleepMs 400};throw 'KV_PROGRAM_BODY_INVALID_MNEMONIC'};$rootAfter=[Windows.Automation.AutomationElement]::FromHandle($p.MainWindowHandle);$insertAfter=$rootAfter.FindFirst([Windows.Automation.TreeScope]::Descendants,$insertCond);if($insertAfter){throw 'KV_EDIT_LIST_NOT_CLOSED'};Invoke-KvGuardedSendKeys -TargetHwnd $p.MainWindowHandle -Step 'program_body_save' -Keys '^s' -ExpectedTitleLike 'KV STUDIO*' -SleepMs 500
[ordered]@{ok=$true;operation='set_fb_program_body';fb_module=$FbModuleName;mnm_path=$MnmPath;project_path=$ProjectPath;program_body_rows=@($text -split "`r?`n"|Where-Object {$_}).Count;modal_closed=$true}|ConvertTo-Json|Set-Content (Join-Path $OutDir 'program_body_result.json') -Encoding UTF8





